version: 1
labels:
  # VERSION LABELS
  - label: major
    branch: "^major/.+"
  - label: minor
    branch: "^scenario/.+"
  - label: patch
    branch: "^chore/.+"
  - label: patch
    branch: "^bug/.+"
  - label: patch
    branch: "^hotfix/.+"
  - label: patch
    branch: "^cleanup/.+"
  - label: patch
    branch: "^enhancement/.+"

  # Impact Labels
  - label: inform-customer
    branch: "^major/.+"
  - label: inform-customer
    branch: "^scenario/.+"
  - label: inform-customer
    branch: "^hotfix/.+"
  - label: inform-customer
    branch: "^bug/.+"
  - label: inform-customer
    branch: "^enhancement/.+"
  - label: immediate-delivery
    branch: "^hotfix/.+"

  # Boundary Labels


  # Type Labels
  - label: scenario
    branch: "^scenario/.+"
  - label: hotfix
    branch: "^hotfix/.+"
  - label: bug
    branch: "^hotfix/.+"
  - label: bug
    branch: "^fix/.+"
  - label: bug
    branch: "^bug/.+"
  - label: documentation
    files:
      - "*.md"
      - "docs/*"
  - label: "infrastructure"
    files:
      - "terraform/*"
      - "infrastructure/*"
      - "infrastructure-config/*"
      - "*.tf"
      - "*.tfvars"
  - label: "build definition"
    files:
      - ".github/*"
      - "build.yml"
      - "build.xml"
      - "docker-compose.yml"
      - "docker/*"
      - ".dockerignore"
      - "make/*"
      - "develop/ansible/*"
      - "develop/docker/*"
  - label: "data"
    files:
      - "database/*"
  - label: "tests"
    files:
      - "tests/*"

  # PR Size Labels
  - label: "PR-Size: S"
    size-below: 50
  - label: "PR-Size: M"
    size-above: 49
    size-below: 333
  - label: "PR-Size: L"
    size-above: 332

  # QA Label
  - label: "qa"
    files:
      - app/*
      - config/*
      - database/*
  - label: qa
    branch: "^major/.+"
  - label: qa
    branch: "^feature/.+"
  - label: qa
    branch: "^enhancement/.+"
  - label: "qa"
    branch: "^hotfix/.+"
