name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint

    - name: Format check
      run: npm run format-check

    - name: Build
      run: npm run build

    - name: Run tests
      run: npm test

  test-action:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Test Action
      id: test-action
      uses: ./
      with:
        config-json: |
          {
            "packageSources": [
              {
                "name": "NuGet",
                "url": "https://api.nuget.org/v3/index.json"
              }
            ]
          }
        output-path: 'test-nuget.config'

    - name: Verify Output
      run: |
        if [ ! -f "test-nuget.config" ]; then
          echo "Output file was not created"
          exit 1
        fi
        if ! grep -q "api.nuget.org" "test-nuget.config"; then
          echo "Output file does not contain expected content"
          exit 1
        fi
