name: Main Branch
on:
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yml
  administration:
    runs-on: ubuntu-latest
    steps:
      - name: Draft Release
        id: draft-release
        uses: release-drafter/release-drafter@v6
        with:
          disable-autolabeler: true
          publish: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
