name: Release
on:
  release:
    types:
      - published

jobs:
  test:
    uses: ./.github/workflows/test.yml
  release:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Generate tags
        id: tags
        uses: actions/github-script@v7
        with:
          script: |
            const version = "${{ github.event.release.tag_name }}"
            const major = version.split('.')[0]
            const minor = version.split('.')[1]

            core.setOutput('major', major)
            core.setOutput('minor', [major, minor].join('.'))
      - name: Set Major release tag
        uses: rickstaa/action-create-tag@v1.7.2
        id: major
        with:
          tag: ${{ steps.tags.outputs.major }}
          force_push_tag: true
      - name: Set Minor release tag
        uses: rickstaa/action-create-tag@v1.7.2
        id: minor
        with:
          tag: ${{ steps.tags.outputs.minor }}
          force_push_tag: true
      - name: Set Latest release tag
        uses: rickstaa/action-create-tag@v1.7.2
        id: latest
        with:
          tag: latest
          force_push_tag: true
